# Generated by Django 4.2.5 on 2023-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vets',
            name='vLink',
            field=models.URLField(default='null', max_length=500),
        ),
    ]
